<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "entity_product"
 *
 * Auto generated by Extension Builder 2020-12-08
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
	'title' => 'Entity Product',
	'description' => 'Product database based on the entity extension',
	'category' => 'plugin',
	'author' => 'Christian Pschorr',
	'author_email' => 'pschorr.christian@gmail.com',
	'state' => 'beta',
	'uploadfolder' => 0,
	'clearCacheOnLoad' => 0,
	'version' => '2.0.0',
	'constraints' => [
		'depends' => [
			'typo3' => '12.0.0-12.4.99',
			'entity' => '2.0.0-2.10.99',
			'flux' => '10.0.10-10.9.99',
		],
		'conflicts' => [],
		'suggests' => [],
	],
];
