<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "entity_product"
 *
 * Auto generated by Extension Builder 2020-12-08
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
	'title' => 'Product',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Christian Pschorr',
	'author_email' => 'pschorr.christian@gmail.com',
	'state' => 'beta',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.1',
	'constraints' => [
		'depends' => [
			'typo3' => '10.4.0-10.4.99',
			'entity' => '0.1.0-1.10.99',
			'flux' => '9.4.2-9.5.99',
			'chart' => '1.0.0-1.10.99',
			'ce_hero' => '1.0.2-1.10.99',
			'ce_downloads' => '1.0.0-1.10.99',
			'ce_marker' => '1.0.0-1.10.99',
			'teaser' => '1.0.0-1.10.99',
		],
		'conflicts' => [],
		'suggests' => [],
	],
];
