routeEnhancers:
  EntityFrontend:
    type: Extbase
    limitToPages: [48]
    extension: Entity
    plugin: Frontend
    routes:
      - { routePath: '/{page}', _controller: 'Entity::list', _arguments: {'page': '@widget_0/currentPage'} }
      - { routePath: '/{entity}', _controller: 'Entity::show', _arguments: {'entity': 'entity'} }
    defaultController: 'Entity::list'
    defaults:
      page: '0'
    requirements:
      page: '\d+'
    aspects:
      page:
        type: StaticRangeMapper
        start: '1'
        end: '100'
      entity:
        type: PersistedAliasMapper
        tableName: tx_entity_domain_model_entity
        routeFieldName: slug
