routeEnhancers:
  EntityProductFrontend:
    type: Extbase
    limitToPages: [ 60, 67, 59, 66 ]
    extension: EntityProduct
    plugin: Frontend
    routes:
      - { routePath: '/{page}', _controller: 'Product::list', _arguments: { 'page': '@widget_0/currentPage' } }
      - { routePath: '/{product}', _controller: 'Product::show', _arguments: { 'product': 'product' } }
    defaultController: 'Product::list'
    defaults:
      page: '0'
    requirements:
      page: '\d+'
    aspects:
      page:
        type: StaticRangeMapper
        start: '1'
        end: '100'
      product:
        type: PersistedAliasMapper
        tableName: tx_entity_domain_model_entity
        routeFieldName: slug
