services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Ps\EntityProduct\:
    resource: '../Classes/*'

  Ps\EntityProduct\EventListener\CanonicalTagEventListener:
    tags:
      - name: event.listener
        identifier: 'entityproduct.canonical'
        event: TYPO3\CMS\Seo\Event\ModifyUrlForCanonicalTagEvent
        after: 'beforeGeneratingCanonical'

  Ps\EntityProduct\EventListener\HrefLangTagEventListener:
    tags:
      - name: event.listener
        identifier: 'entityproduct.hreflang'
        event: TYPO3\CMS\Frontend\Event\ModifyHrefLangTagsEvent
        after: 'typo3-seo/hreflangGenerator'